# Generated by Django 3.2.11 on 2025-08-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='공개 여부'),
        ),
    ]
